import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:hiddify/utils/custom_loggers.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'config_key_store.g.dart';

/// Holds the 32-byte per-install key that seals `configs/<id>.enc`.
///
/// The key is generated by a CSPRNG on first use and never leaves the device.
/// It is deliberately NOT shipped in the binary: a build-time key would mean one
/// extraction decrypts every install's config forever, whereas a per-install key
/// is worthless to anyone but that device. Losing it is a *recoverable* event —
/// the config is re-derivable from the subscription — which is what makes the
/// per-install choice safe across app updates.
///
/// Storage differs by platform because the Android VPN service (`:bg`) and the
/// iOS Network Extension must be able to read the same key with no Flutter
/// engine alive:
///
/// * **Android and iOS** — owned natively (`ConfigKey.kt`, `ConfigKey.swift`) and
///   fetched over the existing `com.raynlabs.app/platform` channel. Android
///   wraps the key with an AndroidKeyStore AES key; iOS stores it in the shared
///   app-group keychain with `AfterFirstUnlockThisDeviceOnly` accessibility. Both
///   are read directly by the `:bg` service and the packet-tunnel extension,
///   which is why the key cannot live inside `flutter_secure_storage` — reading
///   its private storage from another process would couple those shells to
///   plugin internals across upgrades.
/// * **Windows / macOS** — `flutter_secure_storage` (DPAPI / Keychain). The core
///   runs in-process there, so only Dart ever needs the key.
///
/// Linux is not a supported platform and gets no fallback.
class ConfigKeyStore with InfraLogger {
  ConfigKeyStore({FlutterSecureStorage? storage, MethodChannel? channel})
    : _storage = storage ?? const FlutterSecureStorage(),
      _channel = channel ?? const MethodChannel(_channelName);

  static const _channelName = 'com.raynlabs.app/platform';
  static const _getConfigKeyMethod = 'get_config_key';

  /// DPAPI/Keychain entry name on the desktop platforms. Distinct from
  /// `rayn_session_token` — different lifetime, different blast radius.
  static const _storageKey = 'rayn_config_key';

  static const keyLength = 32;

  final FlutterSecureStorage _storage;
  final MethodChannel _channel;

  Uint8List? _cached;
  bool _overridden = false;
  Future<Uint8List?>? _inflight;

  /// Returns the per-install key, creating it on first use, or null if the
  /// platform keystore is unavailable.
  ///
  /// The result is cached for the process lifetime. It is deliberately NOT
  /// scrubbed after use, unlike the `rayn://` link key: this key is read on
  /// every profile write and every connect, and zeroing a cached buffer would
  /// defeat the cache while buying nothing — the plaintext config it protects
  /// is sitting in the same heap anyway.
  Future<Uint8List?> get() async {
    if (_overridden) return _cached;
    final cached = _cached;
    if (cached != null) return cached;
    // Two concurrent first-callers must not both generate a key, or one of them
    // would seal a config under a key the other is about to overwrite.
    return _inflight ??= _resolve().whenComplete(() => _inflight = null);
  }

  Future<Uint8List?> _resolve() async {
    try {
      final key = (Platform.isAndroid || Platform.isIOS)
          ? await _fromPlatformChannel()
          : await _fromSecureStorage();
      if (key == null) return null;
      if (key.length != keyLength) {
        loggy.error('config key is ${key.length} bytes, expected $keyLength');
        return null;
      }
      return _cached = key;
    } catch (e) {
      // Never log `e` itself — a platform exception can carry key material.
      loggy.error('config key unavailable (${e.runtimeType})');
      return null;
    }
  }

  /// Android / iOS: the native side generates on first call and returns the key.
  /// Creation happens only here, in the app process — the `:bg` service and the
  /// packet-tunnel extension use read-only accessors, so a background start can
  /// never race the app into creating a second key and orphaning every config
  /// already on disk.
  Future<Uint8List?> _fromPlatformChannel() => _channel.invokeMethod<Uint8List>(_getConfigKeyMethod);

  Future<Uint8List?> _fromSecureStorage() async {
    final existing = await _storage.read(key: _storageKey);
    if (existing != null && existing.isNotEmpty) {
      try {
        return Uint8List.fromList(base64Decode(existing));
      } catch (_) {
        loggy.warning('stored config key is not valid base64 — regenerating');
      }
    }
    final fresh = _generate();
    await _storage.write(key: _storageKey, value: base64Encode(fresh));
    loggy.info('generated a new per-install config key');
    return fresh;
  }

  static Uint8List _generate() {
    final rng = Random.secure();
    return Uint8List.fromList(List<int>.generate(keyLength, (_) => rng.nextInt(256)));
  }

  /// Test seam. Once called (including with null) the platform keystore is
  /// bypassed for the lifetime of this instance, so a test can pin the
  /// "no key available" state as well as a known key.
  @visibleForTesting
  void debugSetKey(Uint8List? key) {
    _cached = key;
    _overridden = true;
    _inflight = null;
  }
}

@Riverpod(keepAlive: true)
ConfigKeyStore configKeyStore(Ref ref) => ConfigKeyStore();
