package com.raynlabs.app

import android.util.Log
import java.io.File
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Opens the sealed sing-box config the Flutter side writes to `configs/<id>.enc`.
 *
 * Wire format, identical in Dart (`ProfileConfigCipher`) and Swift:
 *
 *     version(1) = 0x01 || nonce(12) || ciphertext || tag(16)
 *     AAD        = utf8(profileId)
 *
 * `AES/GCM/NoPadding` expects `ciphertext||tag` concatenated, which is exactly
 * our layout — do not split the trailing tag off.
 *
 * Read-only by design. Dart is the only writer; this side exists solely so the
 * VPN service can start from the quick-settings tile or an always-on trigger
 * with no Flutter engine alive.
 */
object ConfigCipher {
    private const val TAG = "A/ConfigCipher"
    private const val VERSION_V1: Byte = 0x01
    private const val NONCE_LEN = 12
    private const val TAG_BITS = 128
    private const val MIN_LEN = 1 + NONCE_LEN + 16

    /**
     * The profile id doubles as the AAD, and is the file's base name — the Dart
     * side writes `configs/<profileId>.enc` and nothing else lives there. Keeping
     * one source of truth beats threading a second value through
     * SharedPreferences, where it could drift out of step with the path.
     */
    fun profileIdFor(path: String): String = File(path).name.removeSuffix(".enc")

    /** Returns the sing-box JSON, or null if it cannot be opened for any reason. */
    fun open(path: String, key: ByteArray): String? {
        val file = File(path)
        if (!file.isFile) {
            Log.w(TAG, "no sealed config at the recorded path")
            return null
        }
        return try {
            openBlob(file.readBytes(), profileIdFor(path), key)
        } catch (e: Exception) {
            Log.w(TAG, "sealed config unreadable: ${e.javaClass.simpleName}")
            null
        }
    }

    fun openBlob(blob: ByteArray, profileId: String, key: ByteArray): String? {
        if (blob.size < MIN_LEN) {
            Log.w(TAG, "sealed config too short")
            return null
        }
        if (blob[0] != VERSION_V1) {
            // Written by a newer build than this one. Same remedy as any other
            // failure: the app re-fetches and re-seals.
            Log.w(TAG, "sealed config version ${blob[0]} is not supported")
            return null
        }
        return try {
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(
                Cipher.DECRYPT_MODE,
                SecretKeySpec(key, "AES"),
                GCMParameterSpec(TAG_BITS, blob, 1, NONCE_LEN)
            )
            cipher.updateAAD(profileId.toByteArray(Charsets.UTF_8))
            val plain = cipher.doFinal(blob, 1 + NONCE_LEN, blob.size - 1 - NONCE_LEN)
            String(plain, Charsets.UTF_8)
        } catch (e: Exception) {
            // Wrong key, wrong profile id, truncation or tampering. Report the
            // exception type only — never the body, and never the plaintext.
            Log.w(TAG, "sealed config failed authentication: ${e.javaClass.simpleName}")
            null
        }
    }

    /**
     * Cross-language conformance check against the same vector asserted in
     * `test/features/profile/data/profile_config_cipher_test.dart`, generated by
     * an independent Go implementation.
     *
     * Runs in debug builds only. Three separate AES-GCM implementations read
     * this envelope (Dart, Kotlin, Swift) and a mismatch in nonce placement, tag
     * position or AAD would otherwise surface as "the tunnel won't start from
     * the tile" on one platform, months later. A proper JVM unit test would be
     * better; the app has no test source set and adding one needs a JUnit
     * dependency, so this is the version that costs nothing.
     */
    fun debugSelfTest() {
        val key = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        val blob = hex(
            "01a1b2c3d4e5f60718293a4b5c79040e8ceb5008bdda614aa40c2f2722b3bac4" +
                "fc186a28bec71c6cf161a58f5e5c9ee0a01476345a1960706a8fb6fcc61a9ae0" +
                "1efc77dc85e9361c16d47767f071e24308"
        )
        val expected = """{"outbounds":[{"tag":"conformance","type":"vless"}]}"""
        val actual = openBlob(blob, "6f9619ff-8b86-d011-b42d-00c04fc964ff", key)
        if (actual == expected) {
            Log.d(TAG, "conformance vector OK")
        } else {
            Log.e(TAG, "CONFORMANCE VECTOR FAILED — this build cannot open configs written by the app")
        }
    }

    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { ((Character.digit(s[it * 2], 16) shl 4) + Character.digit(s[it * 2 + 1], 16)).toByte() }
}
