// Regenerates `lib/utils/rayn_link_key_data.dart` — the in-binary material the
// `rayn://import/<token>` AES-256-GCM decrypt key is reconstructed from.
//
//   RAYN_LINK_SECRET=<secret> dart run tool/gen_rayn_link_key.dart --require-secret
//   dart run tool/gen_rayn_link_key.dart                 # dev key, for local work
//
// The secret is read from the ENVIRONMENT, never argv — argv is visible in
// process listings and is echoed by most CI runners.
//
// WHAT IS EMBEDDED
// The client only ever needs `K = SHA-256(utf8(RAYN_LINK_SECRET))`, so the
// secret string itself never enters the binary. K is not stored either; the
// file holds two tables from which K is recomputed at decrypt time:
//
//   salt = 16 random bytes                     (per build)
//   A    = 32 random bytes                     (per build)
//   S    = SHA-256(salt)
//   C[i] = K[i] ^ A[i] ^ S[i] ^ (i & 0xFF)
//   blob = interleave(A, C)                    // A[0],C[0],A[1],C[1],…  64 bytes
//   r    = salt[0] & 0x3F                      // rotation, DERIVED not stored
//   emit   rotateRight(blob, r), salt
//
// The reconstruction in `raynLinkKey()` (lib/utils/rayn_link_key.dart) MUST stay
// byte-for-byte inverse to this. Both tables are re-randomised on every run, so
// two builds of the same secret share no byte layout.
//
// THIS IS OBFUSCATION, NOT A SECRET STORE. The key is public by construction —
// it ships in every binary we publish. It raises a static extraction from
// "minutes with `strings`" to "hours with a disassembler"; it does not survive a
// debugger, and it must never be relied on as a security boundary. See
// RAYN-LINK-SYMMETRIC-MIGRATION.md §2.
//
// To rotate: get the new secret out of band, re-run with --require-secret, ship.
// No core/WSL rebuild is needed — this is Dart, bundled by `flutter build`.
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

/// Used when `RAYN_LINK_SECRET` is absent and `--require-secret` was not passed.
/// Keeps a fresh clone able to run `flutter analyze`, `flutter test` and
/// `flutter run` with no setup. Release targets pass `--require-secret`, so this
/// can never reach a shipped artifact.
const _devSecret = 'rayn-link-development-key-do-not-ship';

const _outputPath = 'lib/utils/rayn_link_key_data.dart';

void main(List<String> args) {
  final requireSecret = args.contains('--require-secret');
  final secret = Platform.environment['RAYN_LINK_SECRET'];
  final isDev = secret == null || secret.isEmpty;

  if (isDev && requireSecret) {
    stderr.writeln(
      'gen_rayn_link_key: RAYN_LINK_SECRET is not set.\n'
      'Refusing to generate a release key file with the development secret.\n'
      'Set RAYN_LINK_SECRET in the environment (never on the command line).',
    );
    exit(1);
  }

  final effective = isDev ? _devSecret : secret;

  // §6.3: SHA-256 of the secret STRING's UTF-8 bytes. The secret is generated
  // with `openssl rand -hex 32` so it LOOKS like hex — do not hex-decode it
  // first, or every link fails authentication.
  final k = Uint8List.fromList(sha256.convert(utf8.encode(effective)).bytes);

  final rand = Random.secure();
  final salt = Uint8List.fromList(List<int>.generate(16, (_) => rand.nextInt(256)));
  final a = Uint8List.fromList(List<int>.generate(32, (_) => rand.nextInt(256)));
  final s = sha256.convert(salt).bytes;

  final interleaved = Uint8List(64);
  for (var i = 0; i < 32; i++) {
    interleaved[2 * i] = a[i];
    interleaved[2 * i + 1] = k[i] ^ a[i] ^ s[i] ^ (i & 0xFF);
  }

  final r = salt[0] & 0x3F;
  final blob = Uint8List(64);
  for (var i = 0; i < 64; i++) {
    blob[(i + r) & 0x3F] = interleaved[i];
  }

  // A one-way commitment to K, safe to print and to embed: it identifies which
  // secret a build was cut with (for matching against the backend) without
  // revealing any part of the key.
  final keyId = sha256.convert(k).bytes.sublist(0, 4).map((b) => b.toRadixString(16).padLeft(2, '0')).join();

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/gen_rayn_link_key.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Masked material for the rayn://import/ AES-256-GCM decrypt key, recombined')
    ..writeln('// in raynLinkKey(). Neither the secret nor the key appears here; both tables')
    ..writeln('// are re-randomised on every generation. Obfuscation only — NOT a secret')
    ..writeln('// store. Regenerate via: dart run tool/gen_rayn_link_key.dart')
    ..writeln()
    ..writeln("part of 'rayn_link_key.dart';")
    ..writeln()
    ..writeln('/// True when this file was generated from the development secret rather than')
    ..writeln('/// a real `RAYN_LINK_SECRET`. Release builds pass `--require-secret`, so a')
    ..writeln('/// shipped artifact with this set to true is a broken build pipeline.')
    ..writeln('const bool kRaynLinkKeyIsDev = $isDev;')
    ..writeln()
    ..writeln('/// One-way commitment to the derived key (first 4 bytes of SHA-256 over it).')
    ..writeln('/// Safe to log — identifies which secret a build was cut with, reveals nothing.')
    ..writeln("const String kRaynLinkKeyId = '$keyId';")
    ..writeln();

  _writeTable(buf, '_t0', blob);
  buf.writeln();
  _writeTable(buf, '_t1', salt);

  File(_outputPath).writeAsStringSync(buf.toString());
  stdout.writeln(
    'wrote $_outputPath (key id $keyId${isDev ? ', DEVELOPMENT SECRET' : ''})',
  );
}

void _writeTable(StringBuffer buf, String name, Uint8List bytes) {
  buf.writeln('const List<int> $name = <int>[');
  for (var i = 0; i < bytes.length; i += 16) {
    final end = (i + 16) < bytes.length ? i + 16 : bytes.length;
    buf.writeln('  ${bytes.sublist(i, end).join(', ')},');
  }
  buf.writeln('];');
}
