// Regenerates `lib/utils/rayn_key_data.dart` from a PKCS#8 RSA private-key PEM.
//
//   dart run tool/obfuscate_rayn_key.dart <path-to-rayn_private_key.pem>
//
// This script is the ONLY place the plaintext key is handled. The PEM is NOT
// committed to the repo — pass it from a secure local path. The output is the
// DER bytes XOR'd with a SHA-256-derived, position-dependent keystream so the
// key does not appear as a loose asset and is not recoverable via `strings`.
//
// This is an OBFUSCATION layer, not a secret store: anyone who reverse-engineers
// the binary can still recover the key (it must be reconstructed at runtime to
// decrypt). The scheme's integrity boundary is TLS in transit, not key secrecy
// — see the `project_rayn_crypto_scheme` memory and rayn_token.dart.
//
// The XOR transform here MUST stay byte-for-byte identical to the reconstruction
// in RaynTokenDecryptor.load(). To rotate the key: regenerate with the new PEM.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

/// Must match `RaynTokenDecryptor._maskSeedPhrase`.
const _maskSeedPhrase = 'rayn-token-v1-mask';

void main(List<String> args) {
  if (args.isEmpty) {
    stderr.writeln('usage: dart run tool/obfuscate_rayn_key.dart <key.pem>');
    exit(2);
  }
  final pem = File(args.first).readAsStringSync();
  final b64 = pem.split('\n').where((l) => !l.contains('-----')).join().trim();
  final der = base64.decode(b64);

  final seed = sha256.convert(utf8.encode(_maskSeedPhrase)).bytes;
  final obf = Uint8List(der.length);
  for (var i = 0; i < der.length; i++) {
    obf[i] = der[i] ^ seed[i % seed.length] ^ (i & 0xFF);
  }

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/obfuscate_rayn_key.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// XOR-obfuscated DER bytes of the rayn:// decrypt key, reconstructed in')
    ..writeln('// RaynTokenDecryptor.load(). Obfuscation only — NOT a secret store.')
    ..writeln('// Regenerate via: dart run tool/obfuscate_rayn_key.dart <key.pem>')
    ..writeln()
    ..writeln('const List<int> obfuscatedRaynKeyDer = <int>[');
  for (var i = 0; i < obf.length; i += 16) {
    final end = (i + 16) < obf.length ? i + 16 : obf.length;
    buf.writeln('  ${obf.sublist(i, end).join(', ')},');
  }
  buf.writeln('];');

  File('lib/utils/rayn_key_data.dart').writeAsStringSync(buf.toString());
  stdout.writeln('wrote lib/utils/rayn_key_data.dart (${obf.length} DER bytes)');
}
