// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsRaynBilling(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsRaynBilling(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsRaynBilling(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashRaynBilling(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashRaynBilling(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashRaynBilling(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum BillingConnState: Int {
  /// Connected and ready to query/purchase.
  case connected = 0
  /// Play Billing is unavailable on this device (no Play Store / unsupported).
  /// Not reachable on iOS — StoreKit is always present.
  case unavailable = 1
  /// Purchasing is disabled: Play reports the feature unsupported, or Apple's
  /// `AppStore.canMakePayments` is false (e.g. parental restrictions).
  case disabled = 2
}

enum RaynPurchaseState: Int {
  case purchased = 0
  case pending = 1
  case unspecified = 2
}

/// One purchasable offer derived from `ProductDetails.subscriptionOfferDetails`
/// — i.e. a base plan, or an offer (the free trial) attached to a base plan.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RaynOffer: Hashable {
  /// "monthly" | "quarter" | "annual" — Play Console base-plan IDs, and on
  /// Apple the suffix of the per-tier product id (`rayn_premium_monthly`).
  var basePlanId: String
  /// Offer id (e.g. "trial"); null for the plain base plan with no offer.
  var offerId: String? = nil
  /// Opaque token passed verbatim to `launchPurchase` — selects this exact
  /// base-plan/offer in the billing flow. Play: the `offerToken`. Apple: the
  /// product id, which is what resolves back to a `Product`.
  var offerToken: String
  /// Localized, currency-correct price for display, e.g. "$19.99" / "₹1,699.00".
  var formattedPrice: String
  /// Price in micros (1,000,000 = one unit) for computing per-month equivalents.
  var priceAmountMicros: Int64
  /// ISO-4217 code, e.g. "USD".
  var priceCurrencyCode: String
  /// ISO-8601 billing period of the recurring phase: "P1M" | "P3M" | "P1Y".
  var billingPeriodIso: String
  /// Whether this offer leads with a free-trial phase (priceAmountMicros == 0).
  var isTrial: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RaynOffer? {
    let basePlanId = pigeonVar_list[0] as! String
    let offerId: String? = nilOrValue(pigeonVar_list[1])
    let offerToken = pigeonVar_list[2] as! String
    let formattedPrice = pigeonVar_list[3] as! String
    let priceAmountMicros = pigeonVar_list[4] as! Int64
    let priceCurrencyCode = pigeonVar_list[5] as! String
    let billingPeriodIso = pigeonVar_list[6] as! String
    let isTrial = pigeonVar_list[7] as! Bool

    return RaynOffer(
      basePlanId: basePlanId,
      offerId: offerId,
      offerToken: offerToken,
      formattedPrice: formattedPrice,
      priceAmountMicros: priceAmountMicros,
      priceCurrencyCode: priceCurrencyCode,
      billingPeriodIso: billingPeriodIso,
      isTrial: isTrial
    )
  }
  func toList() -> [Any?] {
    return [
      basePlanId,
      offerId,
      offerToken,
      formattedPrice,
      priceAmountMicros,
      priceCurrencyCode,
      billingPeriodIso,
      isTrial,
    ]
  }
  static func == (lhs: RaynOffer, rhs: RaynOffer) -> Bool {
    return deepEqualsRaynBilling(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRaynBilling(value: toList(), hasher: &hasher)
  }
}

/// A Play `Purchase` reduced to what the backend verify call needs.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RaynPurchase: Hashable {
  /// The store's opaque identifier for this purchase, sent to the backend's
  /// verify endpoint. Play: `Purchase.getPurchaseToken()`, posted as
  /// `purchaseToken`. Apple: `String(Transaction.id)`, posted as
  /// `transactionId` — a JSON STRING; encoding Apple's `UInt64` as a number
  /// is a 400.
  var purchaseToken: String
  /// The subscription product id: `rayn_premium` on Play (one product carrying
  /// every base plan), or the per-tier id on Apple (`rayn_premium_monthly`).
  var productId: String
  var state: RaynPurchaseState
  /// Already settled server-side. Play: the backend acknowledged it. Apple: we
  /// already called [RaynBilling.finishPurchase], which only ever happens after
  /// a backend 200 — so the meaning carries. Lets the re-verify loop skip
  /// purchases that are already bound.
  var isAcknowledged: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RaynPurchase? {
    let purchaseToken = pigeonVar_list[0] as! String
    let productId = pigeonVar_list[1] as! String
    let state = pigeonVar_list[2] as! RaynPurchaseState
    let isAcknowledged = pigeonVar_list[3] as! Bool

    return RaynPurchase(
      purchaseToken: purchaseToken,
      productId: productId,
      state: state,
      isAcknowledged: isAcknowledged
    )
  }
  func toList() -> [Any?] {
    return [
      purchaseToken,
      productId,
      state,
      isAcknowledged,
    ]
  }
  static func == (lhs: RaynPurchase, rhs: RaynPurchase) -> Bool {
    return deepEqualsRaynBilling(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRaynBilling(value: toList(), hasher: &hasher)
  }
}

/// Synchronous result of `launchBillingFlow` — only reports whether the sheet
/// opened. The actual purchase arrives later via [RaynBillingEvents].
///
/// Generated class from Pigeon that represents data sent in messages.
struct LaunchResult: Hashable {
  /// Play `BillingResponseCode` (0 = OK, 1 = USER_CANCELED, 7 = ITEM_ALREADY
  /// _OWNED, …). The Apple host deliberately emits these same integers, so the
  /// Dart layer needs no per-store branching.
  var responseCode: Int64
  var debugMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LaunchResult? {
    let responseCode = pigeonVar_list[0] as! Int64
    let debugMessage: String? = nilOrValue(pigeonVar_list[1])

    return LaunchResult(
      responseCode: responseCode,
      debugMessage: debugMessage
    )
  }
  func toList() -> [Any?] {
    return [
      responseCode,
      debugMessage,
    ]
  }
  static func == (lhs: LaunchResult, rhs: LaunchResult) -> Bool {
    return deepEqualsRaynBilling(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRaynBilling(value: toList(), hasher: &hasher)
  }
}

private class RaynBillingPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BillingConnState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RaynPurchaseState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return RaynOffer.fromList(self.readValue() as! [Any?])
    case 132:
      return RaynPurchase.fromList(self.readValue() as! [Any?])
    case 133:
      return LaunchResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class RaynBillingPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BillingConnState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RaynPurchaseState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? RaynOffer {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RaynPurchase {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? LaunchResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class RaynBillingPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RaynBillingPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RaynBillingPigeonCodecWriter(data: data)
  }
}

class RaynBillingPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = RaynBillingPigeonCodec(readerWriter: RaynBillingPigeonCodecReaderWriter())
}


/// Dart -> Kotlin. Calls we initiate against the BillingClient.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RaynBilling {
  /// Build + connect the BillingClient (idempotent; reconnects if dropped).
  func connect(completion: @escaping (Result<BillingConnState, Error>) -> Void)
  /// Query the purchasable offers for [productId].
  ///
  /// Play: one product (`rayn_premium`) carrying the base plans plus the trial
  /// offer. Apple: [productId] names the subscription GROUP, which the host
  /// expands into one product per base plan (`<productId>_<basePlanId>`) and
  /// returns a single offer for each.
  func queryOffers(productId: String, completion: @escaping (Result<[RaynOffer], Error>) -> Void)
  /// Launch the purchase UI for [offerToken], binding the purchase to the
  /// account: Play `setObfuscatedAccountId`, Apple `.appAccountToken`. Both
  /// take the raw lowercase RouteKey `user_id`; Apple additionally requires it
  /// to parse as a UUID, and the host omits the option rather than send a
  /// fabricated value. Not @async — it returns immediately; the purchase
  /// comes back through [RaynBillingEvents].
  func launchPurchase(offerToken: String, obfuscatedAccountId: String) throws -> LaunchResult
  /// Active subscription purchases — drives re-verify-on-launch and
  /// restore-on-reinstall. Play: `queryPurchasesAsync`. Apple: the union of
  /// `Transaction.currentEntitlements` and `Transaction.unfinished`, so an
  /// interrupted verify is replayed as well as a reinstall.
  func queryActivePurchases(completion: @escaping (Result<[RaynPurchase], Error>) -> Void)
  /// Tell the store this purchase has been delivered.
  ///
  /// Apple-only in effect. StoreKit redelivers an unfinished transaction
  /// forever, so it has to be finished once the BACKEND has confirmed it —
  /// this is delivery confirmation, NOT acknowledgement, and entitlement still
  /// follows the backend. Dart calls it from exactly one place: immediately
  /// after `verify` returns 200. Play never acknowledges locally, so its
  /// implementation is a deliberate no-op.
  func finishPurchase(purchaseToken: String) throws
  /// Tear down the store connection (e.g. on logout / app dispose).
  func endConnection() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RaynBillingSetup {
  static var codec: FlutterStandardMessageCodec { RaynBillingPigeonCodec.shared }
  /// Sets up an instance of `RaynBilling` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RaynBilling?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Build + connect the BillingClient (idempotent; reconnects if dropped).
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rayn.RaynBilling.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { _, reply in
        api.connect { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    /// Query the purchasable offers for [productId].
    ///
    /// Play: one product (`rayn_premium`) carrying the base plans plus the trial
    /// offer. Apple: [productId] names the subscription GROUP, which the host
    /// expands into one product per base plan (`<productId>_<basePlanId>`) and
    /// returns a single offer for each.
    let queryOffersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rayn.RaynBilling.queryOffers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryOffersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let productIdArg = args[0] as! String
        api.queryOffers(productId: productIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryOffersChannel.setMessageHandler(nil)
    }
    /// Launch the purchase UI for [offerToken], binding the purchase to the
    /// account: Play `setObfuscatedAccountId`, Apple `.appAccountToken`. Both
    /// take the raw lowercase RouteKey `user_id`; Apple additionally requires it
    /// to parse as a UUID, and the host omits the option rather than send a
    /// fabricated value. Not @async — it returns immediately; the purchase
    /// comes back through [RaynBillingEvents].
    let launchPurchaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rayn.RaynBilling.launchPurchase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchPurchaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let offerTokenArg = args[0] as! String
        let obfuscatedAccountIdArg = args[1] as! String
        do {
          let result = try api.launchPurchase(offerToken: offerTokenArg, obfuscatedAccountId: obfuscatedAccountIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      launchPurchaseChannel.setMessageHandler(nil)
    }
    /// Active subscription purchases — drives re-verify-on-launch and
    /// restore-on-reinstall. Play: `queryPurchasesAsync`. Apple: the union of
    /// `Transaction.currentEntitlements` and `Transaction.unfinished`, so an
    /// interrupted verify is replayed as well as a reinstall.
    let queryActivePurchasesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rayn.RaynBilling.queryActivePurchases\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryActivePurchasesChannel.setMessageHandler { _, reply in
        api.queryActivePurchases { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryActivePurchasesChannel.setMessageHandler(nil)
    }
    /// Tell the store this purchase has been delivered.
    ///
    /// Apple-only in effect. StoreKit redelivers an unfinished transaction
    /// forever, so it has to be finished once the BACKEND has confirmed it —
    /// this is delivery confirmation, NOT acknowledgement, and entitlement still
    /// follows the backend. Dart calls it from exactly one place: immediately
    /// after `verify` returns 200. Play never acknowledges locally, so its
    /// implementation is a deliberate no-op.
    let finishPurchaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rayn.RaynBilling.finishPurchase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      finishPurchaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let purchaseTokenArg = args[0] as! String
        do {
          try api.finishPurchase(purchaseToken: purchaseTokenArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      finishPurchaseChannel.setMessageHandler(nil)
    }
    /// Tear down the store connection (e.g. on logout / app dispose).
    let endConnectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rayn.RaynBilling.endConnection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endConnectionChannel.setMessageHandler { _, reply in
        do {
          try api.endConnection()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      endConnectionChannel.setMessageHandler(nil)
    }
  }
}
/// Kotlin -> Dart. Play's asynchronous push events.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol RaynBillingEventsProtocol {
  /// From `PurchasesUpdatedListener`. Dart verifies PURCHASED items, shows
  /// "processing" for PENDING, and resets the UI on USER_CANCELED.
  func onPurchasesUpdated(purchases purchasesArg: [RaynPurchase], responseCode responseCodeArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// From `onBillingServiceDisconnected` — Dart may trigger a reconnect. Never
  /// fired on iOS; StoreKit has no connection to lose.
  func onBillingDisconnected(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class RaynBillingEvents: RaynBillingEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: RaynBillingPigeonCodec {
    return RaynBillingPigeonCodec.shared
  }
  /// From `PurchasesUpdatedListener`. Dart verifies PURCHASED items, shows
  /// "processing" for PENDING, and resets the UI on USER_CANCELED.
  func onPurchasesUpdated(purchases purchasesArg: [RaynPurchase], responseCode responseCodeArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rayn.RaynBillingEvents.onPurchasesUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([purchasesArg, responseCodeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// From `onBillingServiceDisconnected` — Dart may trigger a reconnect. Never
  /// fired on iOS; StoreKit has no connection to lose.
  func onBillingDisconnected(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rayn.RaynBillingEvents.onBillingDisconnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
