// GENERATED by tool/gen_rayn_link_key.dart — do not edit by hand.
//
// Masked material for the rayn://import/ AES-256-GCM decrypt key, recombined
// in raynLinkKey(). Neither the secret nor the key appears here; both tables
// are re-randomised on every generation. Obfuscation only — NOT a secret
// store. Regenerate via: dart run tool/gen_rayn_link_key.dart

part of 'rayn_link_key.dart';

/// True when this file was generated from the development secret rather than
/// a real `RAYN_LINK_SECRET`. Release builds pass `--require-secret`, so a
/// shipped artifact with this set to true is a broken build pipeline.
const bool kRaynLinkKeyIsDev = false;

/// One-way commitment to the derived key (first 4 bytes of SHA-256 over it).
/// Safe to log — identifies which secret a build was cut with, reveals nothing.
const String kRaynLinkKeyId = '12a1ed98';

const List<int> _t0 = <int>[
  35, 123, 32, 99, 16, 245, 167, 145, 114, 197, 240, 255, 52, 149, 197, 144,
  45, 24, 244, 40, 18, 237, 38, 158, 53, 207, 204, 201, 71, 3, 71, 225,
  156, 68, 239, 190, 219, 240, 39, 157, 78, 17, 145, 128, 179, 162, 59, 218,
  185, 21, 159, 61, 174, 85, 155, 91, 16, 239, 86, 107, 65, 6, 141, 104,
];

const List<int> _t1 = <int>[
  178, 83, 210, 236, 122, 43, 204, 121, 74, 29, 66, 48, 188, 248, 176, 35,
];
