// GENERATED by tool/gen_rayn_link_key.dart — do not edit by hand.
//
// Masked material for the rayn://import/ AES-256-GCM decrypt key, recombined
// in raynLinkKey(). Neither the secret nor the key appears here; both tables
// are re-randomised on every generation. Obfuscation only — NOT a secret
// store. Regenerate via: dart run tool/gen_rayn_link_key.dart

part of 'rayn_link_key.dart';

/// True when this file was generated from the development secret rather than
/// a real `RAYN_LINK_SECRET`. Release builds pass `--require-secret`, so a
/// shipped artifact with this set to true is a broken build pipeline.
const bool kRaynLinkKeyIsDev = false;

/// One-way commitment to the derived key (first 4 bytes of SHA-256 over it).
/// Safe to log — identifies which secret a build was cut with, reveals nothing.
const String kRaynLinkKeyId = '12a1ed98';

const List<int> _t0 = <int>[
  203, 205, 222, 129, 97, 69, 202, 69, 121, 64, 235, 133, 240, 114, 109, 180,
  92, 237, 184, 9, 27, 29, 164, 192, 201, 92, 245, 98, 110, 123, 15, 219,
  72, 6, 41, 42, 83, 206, 8, 105, 135, 176, 192, 64, 62, 207, 58, 113,
  247, 7, 217, 251, 105, 255, 189, 78, 214, 156, 129, 175, 2, 244, 89, 142,
];

const List<int> _t1 = <int>[
  40, 206, 11, 106, 46, 215, 4, 173, 224, 108, 134, 136, 9, 62, 144, 0,
];
