// GENERATED by tool/gen_rayn_link_key.dart — do not edit by hand.
//
// Masked material for the rayn://import/ AES-256-GCM decrypt key, recombined
// in raynLinkKey(). Neither the secret nor the key appears here; both tables
// are re-randomised on every generation. Obfuscation only — NOT a secret
// store. Regenerate via: dart run tool/gen_rayn_link_key.dart

part of 'rayn_link_key.dart';

/// True when this file was generated from the development secret rather than
/// a real `RAYN_LINK_SECRET`. Release builds pass `--require-secret`, so a
/// shipped artifact with this set to true is a broken build pipeline.
const bool kRaynLinkKeyIsDev = false;

/// One-way commitment to the derived key (first 4 bytes of SHA-256 over it).
/// Safe to log — identifies which secret a build was cut with, reveals nothing.
const String kRaynLinkKeyId = '12a1ed98';

const List<int> _t0 = <int>[
  136, 38, 193, 18, 113, 76, 250, 163, 114, 104, 4, 149, 254, 89, 115, 106,
  154, 108, 236, 206, 125, 230, 217, 200, 1, 242, 86, 174, 55, 3, 8, 53,
  2, 117, 236, 127, 39, 183, 130, 147, 178, 48, 95, 147, 244, 145, 76, 35,
  77, 16, 155, 210, 197, 9, 254, 124, 105, 71, 185, 98, 27, 139, 77, 24,
];

const List<int> _t1 = <int>[
  78, 250, 211, 232, 216, 200, 106, 128, 32, 100, 99, 96, 229, 70, 131, 119,
];
