//
//  ConfigCipher.swift
//  Shared between Runner and HiddifyPacketTunnel.
//

import CryptoKit
import Foundation
import os.log

/// Opens the sealed sing-box config the Flutter side writes to `configs/<id>.enc`.
///
/// Wire format, identical in Dart (`ProfileConfigCipher`) and Kotlin:
///
///     version(1) = 0x01 || nonce(12) || ciphertext || tag(16)
///     AAD        = utf8(profileId)
///
/// Everything after the version byte is exactly CryptoKit's `combined`
/// representation (`nonce || ciphertext || tag`), so the blob needs no
/// re-assembly beyond dropping that first byte.
///
/// Read-only by design. Dart is the only writer; this exists so the packet
/// tunnel can start on an on-demand trigger with the app not running.
public enum ConfigCipher {
    private static let log = Logger(subsystem: "com.raynlabs.app", category: "ConfigCipher")

    private static let versionV1: UInt8 = 0x01
    private static let nonceLength = 12
    private static let tagLength = 16
    private static let minimumLength = 1 + 12 + 16

    /// Locates the sealed config in the shared container.
    ///
    /// The app enforces a single profile, so `configs/` holds exactly one
    /// `.enc`. Finding it by extension avoids sharing the path with the
    /// extension: `VPNConfig` stores it in `UserDefaults.standard`, which is
    /// per-process and invisible here.
    public static func locateSealedConfig() -> URL? {
        let configs = FilePath.workingDirectory.appendingPathComponent("configs", isDirectory: true)
        guard let entries = try? FileManager.default.contentsOfDirectory(
            at: configs,
            includingPropertiesForKeys: [.contentModificationDateKey]
        ) else { return nil }

        let sealed = entries.filter { $0.pathExtension == "enc" }
        if sealed.count > 1 {
            log.warning("more than one sealed config present; using the most recent")
        }
        return sealed.max { a, b in
            let da = (try? a.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate ?? .distantPast
            let db = (try? b.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate ?? .distantPast
            return da < db
        }
    }

    /// The profile id doubles as the AAD and is the file's base name — the Dart
    /// side writes `configs/<profileId>.enc`. One source of truth beats carrying
    /// the id separately, where it could drift out of step with the file.
    public static func profileId(for url: URL) -> String {
        url.deletingPathExtension().lastPathComponent
    }

    /// Returns the sing-box JSON, or nil if the config cannot be opened for any
    /// reason. Failures are reported by kind — never by value; the plaintext is
    /// the user's node list.
    public static func open(url: URL, key: Data) -> String? {
        guard let blob = try? Data(contentsOf: url) else {
            log.warning("sealed config could not be read")
            return nil
        }
        return open(blob: blob, profileId: profileId(for: url), key: key)
    }

    public static func open(blob: Data, profileId: String, key: Data) -> String? {
        guard blob.count >= minimumLength else {
            log.warning("sealed config too short")
            return nil
        }
        guard blob[blob.startIndex] == versionV1 else {
            // Written by a newer build. Same remedy as any other failure: the
            // app re-fetches and re-seals.
            log.warning("sealed config version is not supported")
            return nil
        }
        do {
            let box = try AES.GCM.SealedBox(combined: blob.dropFirst())
            let plain = try AES.GCM.open(
                box,
                using: SymmetricKey(data: key),
                authenticating: Data(profileId.utf8)
            )
            guard let json = String(data: plain, encoding: .utf8) else {
                log.warning("sealed config plaintext is not valid UTF-8")
                return nil
            }
            return json
        } catch {
            // Wrong key, wrong profile id, truncation or tampering.
            log.warning("sealed config failed authentication")
            return nil
        }
    }

    /// Cross-language conformance check against the same vector asserted in
    /// `test/features/profile/data/profile_config_cipher_test.dart`, generated by
    /// an independent Go implementation.
    ///
    /// Three separate AES-GCM implementations read this envelope (Dart, Kotlin,
    /// Swift). A mismatch in nonce placement, tag position or AAD would
    /// otherwise surface as "the tunnel won't come back on-demand" on one
    /// platform, months later.
    public static func conformanceVectorPasses() -> Bool {
        let key = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let blob = hex(
            "01a1b2c3d4e5f60718293a4b5c79040e8ceb5008bdda614aa40c2f2722b3bac4"
                + "fc186a28bec71c6cf161a58f5e5c9ee0a01476345a1960706a8fb6fcc61a9ae0"
                + "1efc77dc85e9361c16d47767f071e24308"
        )
        let expected = #"{"outbounds":[{"tag":"conformance","type":"vless"}]}"#
        return open(blob: blob, profileId: "6f9619ff-8b86-d011-b42d-00c04fc964ff", key: key) == expected
    }

    private static func hex(_ s: String) -> Data {
        var out = Data(capacity: s.count / 2)
        var index = s.startIndex
        while index < s.endIndex {
            let next = s.index(index, offsetBy: 2)
            out.append(UInt8(s[index..<next], radix: 16) ?? 0)
            index = next
        }
        return out
    }
}
