// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.raynlabs.app.billing

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object RaynBillingPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class BillingConnState(val raw: Int) {
  /** Connected and ready to query/purchase. */
  CONNECTED(0),
  /**
   * Play Billing is unavailable on this device (no Play Store / unsupported).
   * Not reachable on iOS — StoreKit is always present.
   */
  UNAVAILABLE(1),
  /**
   * Purchasing is disabled: Play reports the feature unsupported, or Apple's
   * `AppStore.canMakePayments` is false (e.g. parental restrictions).
   */
  DISABLED(2);

  companion object {
    fun ofRaw(raw: Int): BillingConnState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RaynPurchaseState(val raw: Int) {
  PURCHASED(0),
  PENDING(1),
  UNSPECIFIED(2);

  companion object {
    fun ofRaw(raw: Int): RaynPurchaseState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * One purchasable offer derived from `ProductDetails.subscriptionOfferDetails`
 * — i.e. a base plan, or an offer (the free trial) attached to a base plan.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RaynOffer (
  /**
   * "monthly" | "quarter" | "annual" — Play Console base-plan IDs, and on
   * Apple the suffix of the per-tier product id (`rayn_premium_monthly`).
   */
  val basePlanId: String,
  /** Offer id (e.g. "trial"); null for the plain base plan with no offer. */
  val offerId: String? = null,
  /**
   * Opaque token passed verbatim to `launchPurchase` — selects this exact
   * base-plan/offer in the billing flow. Play: the `offerToken`. Apple: the
   * product id, which is what resolves back to a `Product`.
   */
  val offerToken: String,
  /** Localized, currency-correct price for display, e.g. "$19.99" / "₹1,699.00". */
  val formattedPrice: String,
  /** Price in micros (1,000,000 = one unit) for computing per-month equivalents. */
  val priceAmountMicros: Long,
  /** ISO-4217 code, e.g. "USD". */
  val priceCurrencyCode: String,
  /** ISO-8601 billing period of the recurring phase: "P1M" | "P3M" | "P1Y". */
  val billingPeriodIso: String,
  /** Whether this offer leads with a free-trial phase (priceAmountMicros == 0). */
  val isTrial: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RaynOffer {
      val basePlanId = pigeonVar_list[0] as String
      val offerId = pigeonVar_list[1] as String?
      val offerToken = pigeonVar_list[2] as String
      val formattedPrice = pigeonVar_list[3] as String
      val priceAmountMicros = pigeonVar_list[4] as Long
      val priceCurrencyCode = pigeonVar_list[5] as String
      val billingPeriodIso = pigeonVar_list[6] as String
      val isTrial = pigeonVar_list[7] as Boolean
      return RaynOffer(basePlanId, offerId, offerToken, formattedPrice, priceAmountMicros, priceCurrencyCode, billingPeriodIso, isTrial)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      basePlanId,
      offerId,
      offerToken,
      formattedPrice,
      priceAmountMicros,
      priceCurrencyCode,
      billingPeriodIso,
      isTrial,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RaynOffer) {
      return false
    }
    if (this === other) {
      return true
    }
    return RaynBillingPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A Play `Purchase` reduced to what the backend verify call needs.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RaynPurchase (
  /**
   * The store's opaque identifier for this purchase, sent to the backend's
   * verify endpoint. Play: `Purchase.getPurchaseToken()`, posted as
   * `purchaseToken`. Apple: `String(Transaction.id)`, posted as
   * `transactionId` — a JSON STRING; encoding Apple's `UInt64` as a number
   * is a 400.
   */
  val purchaseToken: String,
  /**
   * The subscription product id: `rayn_premium` on Play (one product carrying
   * every base plan), or the per-tier id on Apple (`rayn_premium_monthly`).
   */
  val productId: String,
  val state: RaynPurchaseState,
  /**
   * Already settled server-side. Play: the backend acknowledged it. Apple: we
   * already called [RaynBilling.finishPurchase], which only ever happens after
   * a backend 200 — so the meaning carries. Lets the re-verify loop skip
   * purchases that are already bound.
   */
  val isAcknowledged: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RaynPurchase {
      val purchaseToken = pigeonVar_list[0] as String
      val productId = pigeonVar_list[1] as String
      val state = pigeonVar_list[2] as RaynPurchaseState
      val isAcknowledged = pigeonVar_list[3] as Boolean
      return RaynPurchase(purchaseToken, productId, state, isAcknowledged)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      purchaseToken,
      productId,
      state,
      isAcknowledged,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RaynPurchase) {
      return false
    }
    if (this === other) {
      return true
    }
    return RaynBillingPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Synchronous result of `launchBillingFlow` — only reports whether the sheet
 * opened. The actual purchase arrives later via [RaynBillingEvents].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LaunchResult (
  /**
   * Play `BillingResponseCode` (0 = OK, 1 = USER_CANCELED, 7 = ITEM_ALREADY
   * _OWNED, …). The Apple host deliberately emits these same integers, so the
   * Dart layer needs no per-store branching.
   */
  val responseCode: Long,
  val debugMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LaunchResult {
      val responseCode = pigeonVar_list[0] as Long
      val debugMessage = pigeonVar_list[1] as String?
      return LaunchResult(responseCode, debugMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      responseCode,
      debugMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LaunchResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return RaynBillingPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class RaynBillingPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BillingConnState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RaynPurchaseState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RaynOffer.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RaynPurchase.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LaunchResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BillingConnState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is RaynPurchaseState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is RaynOffer -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RaynPurchase -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is LaunchResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart -> Kotlin. Calls we initiate against the BillingClient.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface RaynBilling {
  /** Build + connect the BillingClient (idempotent; reconnects if dropped). */
  fun connect(callback: (Result<BillingConnState>) -> Unit)
  /**
   * Query the purchasable offers for [productId].
   *
   * Play: one product (`rayn_premium`) carrying the base plans plus the trial
   * offer. Apple: [productId] names the subscription GROUP, which the host
   * expands into one product per base plan (`<productId>_<basePlanId>`) and
   * returns a single offer for each.
   */
  fun queryOffers(productId: String, callback: (Result<List<RaynOffer>>) -> Unit)
  /**
   * Launch the purchase UI for [offerToken], binding the purchase to the
   * account: Play `setObfuscatedAccountId`, Apple `.appAccountToken`. Both
   * take the raw lowercase RouteKey `user_id`; Apple additionally requires it
   * to parse as a UUID, and the host omits the option rather than send a
   * fabricated value. Not @async — it returns immediately; the purchase
   * comes back through [RaynBillingEvents].
   */
  fun launchPurchase(offerToken: String, obfuscatedAccountId: String): LaunchResult
  /**
   * Active subscription purchases — drives re-verify-on-launch and
   * restore-on-reinstall. Play: `queryPurchasesAsync`. Apple: the union of
   * `Transaction.currentEntitlements` and `Transaction.unfinished`, so an
   * interrupted verify is replayed as well as a reinstall.
   */
  fun queryActivePurchases(callback: (Result<List<RaynPurchase>>) -> Unit)
  /**
   * Tell the store this purchase has been delivered.
   *
   * Apple-only in effect. StoreKit redelivers an unfinished transaction
   * forever, so it has to be finished once the BACKEND has confirmed it —
   * this is delivery confirmation, NOT acknowledgement, and entitlement still
   * follows the backend. Dart calls it from exactly one place: immediately
   * after `verify` returns 200. Play never acknowledges locally, so its
   * implementation is a deliberate no-op.
   */
  fun finishPurchase(purchaseToken: String)
  /** Tear down the store connection (e.g. on logout / app dispose). */
  fun endConnection()

  companion object {
    /** The codec used by RaynBilling. */
    val codec: MessageCodec<Any?> by lazy {
      RaynBillingPigeonCodec()
    }
    /** Sets up an instance of `RaynBilling` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RaynBilling?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hiddify.RaynBilling.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.connect{ result: Result<BillingConnState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaynBillingPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RaynBillingPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hiddify.RaynBilling.queryOffers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val productIdArg = args[0] as String
            api.queryOffers(productIdArg) { result: Result<List<RaynOffer>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaynBillingPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RaynBillingPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hiddify.RaynBilling.launchPurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val offerTokenArg = args[0] as String
            val obfuscatedAccountIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.launchPurchase(offerTokenArg, obfuscatedAccountIdArg))
            } catch (exception: Throwable) {
              RaynBillingPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hiddify.RaynBilling.queryActivePurchases$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.queryActivePurchases{ result: Result<List<RaynPurchase>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaynBillingPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RaynBillingPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hiddify.RaynBilling.finishPurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val purchaseTokenArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.finishPurchase(purchaseTokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              RaynBillingPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hiddify.RaynBilling.endConnection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.endConnection()
              listOf(null)
            } catch (exception: Throwable) {
              RaynBillingPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Kotlin -> Dart. Play's asynchronous push events.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class RaynBillingEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by RaynBillingEvents. */
    val codec: MessageCodec<Any?> by lazy {
      RaynBillingPigeonCodec()
    }
  }
  /**
   * From `PurchasesUpdatedListener`. Dart verifies PURCHASED items, shows
   * "processing" for PENDING, and resets the UI on USER_CANCELED.
   */
  fun onPurchasesUpdated(purchasesArg: List<RaynPurchase>, responseCodeArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hiddify.RaynBillingEvents.onPurchasesUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(purchasesArg, responseCodeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(RaynBillingPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * From `onBillingServiceDisconnected` — Dart may trigger a reconnect. Never
   * fired on iOS; StoreKit has no connection to lose.
   */
  fun onBillingDisconnected(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hiddify.RaynBillingEvents.onBillingDisconnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(RaynBillingPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
